# -*- coding: utf-8 -*-
"""Gabriela Vidales - FDS_Project_LearnerNotebook_FullCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NYp2KBjqqIjE8Oz90dlhqHRBhtTScO9p

# **Project Foundations for Data Science: FoodHub Data Analysis**

*Gabriela Yasmin Vidales Ayala*                            
**Marks: 60**

## **Context**

The number of restaurants in New York is increasing day by day. Lots of students and busy professionals rely on those restaurants due to their hectic lifestyles. Online food delivery service is a great option for them. It provides them with good food from their favorite restaurants. A food aggregator company FoodHub offers access to multiple restaurants through a single smartphone app.

The app allows the restaurants to receive a direct online order from a customer. The app assigns a delivery person from the company to pick up the order after it is confirmed by the restaurant. The delivery person then uses the map to reach the restaurant and waits for the food package. Once the food package is handed over to the delivery person, he/she confirms the pick-up in the app and travels to the customer's location to deliver the food. The delivery person confirms the drop-off in the app after delivering the food package to the customer. The customer can rate the order in the app. The food aggregator earns money by collecting a fixed margin of the delivery order from the restaurants.

## **Objective**

The food aggregator company has stored the data of the different orders made by the registered customers in their online portal. They want to analyze the data to get a fair idea about the demand of different restaurants which will help them in enhancing their customer experience. Suppose you are hired as a Data Scientist in this company and the Data Science team has shared some of the key questions that need to be answered. Perform the data analysis to find answers to these questions that will help the company to improve the business.

## **Data Description**

The data contains the different data related to a food order. The detailed data dictionary is given below.

* order_id: Unique ID of the order
* customer_id: ID of the customer who ordered the food
* restaurant_name: Name of the restaurant
* cuisine_type: Cuisine ordered by the customer
* cost: Cost of the order
* day_of_the_week: Indicates whether the order is placed on a weekday or weekend (The weekday is from Monday to Friday and the weekend is Saturday and Sunday)
* rating: Rating given by the customer out of 5
* food_preparation_time: Time (in minutes) taken by the restaurant to prepare the food. This is calculated by taking the difference between the timestamps of the restaurant's order confirmation and the delivery person's pick-up confirmation.
* delivery_time: Time (in minutes) taken by the delivery person to deliver the food package. This is calculated by taking the difference between the timestamps of the delivery person's pick-up confirmation and drop-off information
"""

# import libraries for data manipulation and vizualitation
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## **Data Overview: Understanding the structure of the data**

### **DataFrame**
"""

# read the data
df = pd.read_csv('foodhub_order.csv')
# returns the first 5 rows
df.head()

df # Return all data

"""#### Observations:

The structure of the DataFrame indicates that it captures both transactional and operational information related to each order, including customer details, restaurant information, order cost, day classification (weekday or weekend), customer rating, preparation time, and delivery time. It has 9 columns as mentioned in the Data Dictionary, and in each row corresponds to the order placed by a customer.

### **Question 1:** How many rows and columns are present in the data? [0.5 mark]
"""

df.shape  # Output format: (row, columns)

"""#### Observations:

The dataset contains 1,898 rows and 9 columns, meaning that 1,898 individual food orders have been recorded along with nine attributes describing each transaction. Each row corresponds to a single completed order placed through the FoodHub platform.

### **Question 2:** What are the datatypes of the different columns in the dataset? (The info() function can be used) [0.5 mark]
"""

df.info()  # Display dataframe structure: column names, non-null counts, data types, and memory usage

"""#### Observations:

From a data type perspective, the dataset includes a combination of numerical and categorical variables.

The columns order_id and customer_id are stored as integers, while cost_of_the_order is recorded as a floating-point variable. Operational performance indicators such as food_preparation_time and delivery_time are also numerical (integer type). Categorical variables include restaurant_name, cuisine_type, day_of_the_week, and rating. This structure allows for both quantitative performance analysis and categorical segmentation.

### **Question 3:** Are there any missing values in the data? If yes, treat them using an appropriate method. [1 mark]
"""

missing = df.isna().sum().sort_values(ascending=False)  # Count NaNs per column and sort from highest to lowest

missing[missing > 0]  # Display only columns that contain missing values

"""The output confirms that no column contains technical missing values (NaN). All 1,898 records are complete across the dataset.

Another way to check for missing data is by using describe(), especially the "count" row. If the count value is lower than the total number of rows in any column, it indicates missing data in that column.
"""

df.describe()

"""The average cost of an order is approximately 16.50, with prices ranging from about 4.47 to 35.41. Food preparation time averages around 27.37 minutes, while delivery time averages approximately 24.16 minutes. The relatively narrow spread between minimum and maximum values suggests operational consistency without extreme outliers.

Although the dataset does not contain technical missing values (NaN), the rating variable includes entries labeled as “Not given,” which represent orders where customers did not provide feedback. These entries are treated as a separate category rather than missing data.
"""

df_clean = df.copy()  # Create a copy to avoid modifying original dataframe

for col in df_clean.columns:  # Loop through each column
    if col == "rating":
        continue  # Skip rating column (handled separately)
    if df_clean[col].isna().any():  # Check for missing values
        if pd.api.types.is_numeric_dtype(df_clean[col]):
            df_clean[col] = df_clean[col].fillna(df_clean[col].median())  # Fill numeric NaNs with median
        else:
            df_clean[col] = df_clean[col].fillna(df_clean[col].mode().iloc[0])  # Fill categorical NaNs with mode

df_clean["rating_label"] = df_clean["rating"].fillna("Not Rated")  # Replace missing ratings

df_clean.isna().sum()  # Show remaining missing values

"""#### Observations:

All columns contain zero missing values, confirming that the dataset is complete and ready for analysis.

A copy of the original dataframe was created to prevent modifying the raw data.Additionally, a new column, rating_label, was created to distinguish orders without a rating (“Not Rated”), allowing for clearer interpretation in customer satisfaction analysis.

### **Question 4:** Check the statistical summary of the data. What is the minimum, average, and maximum time it takes for food to be prepared once an order is placed? [2 marks]
"""

df_clean["food_preparation_time"].agg(["min", "mean", "max"])  # Get min, mean, and max preparation times

stats = df_clean["food_preparation_time"].agg(["min", "mean", "max"])
plt.figure(figsize=(7, 4))  # Create figure with balanced proportions
bars = plt.bar(stats.index, stats.values, color="pink")  # Bar chart for min, mean, max

plt.title("Food Preparation Time Summary", fontweight="bold")
plt.xlabel("Statistic")
plt.ylabel("Time (minutes)")

plt.grid(axis="y", linestyle="--", alpha=0.4)  # Add subtle horizontal grid
plt.tight_layout()
plt.show()

"""#### Observations:
The minimum food preparation time is 20 minutes, the average is approximately 27.37 minutes, and the maximum is 35 minutes. This indicates that preparation times are relatively consistent, with limited variability and no extreme outliers.

### **Question 5:** How many orders are not rated? [1 mark]
"""

df_clean["rating"].isna().sum()  # Count the number of missing (NaN) values in the "rating" column

"""#### Observations:

There are 736 orders that were not rated by customers. This represents a significant portion of the dataset and should be considered when analyzing customer satisfaction, as only rated orders should be used for rating-based insights.
"""

df_clean["rating"].isna()  # Return a boolean Series indicating which values in "rating" are missing (True = NaN)

"""## **Exploratory Data Analysis (EDA): Univariate Analysis**

### **Question 6:** Explore all the variables and provide observations on their distributions. (Generally, histograms, boxplots, countplots, etc. are used for univariate exploration.) [9 marks]
"""

num_cols = ["cost_of_the_order", "food_preparation_time", "delivery_time"]  # Columns of interest
df_clean[num_cols].describe().T  # Summary statistics, better readability

"""#### Observations:

Although order costs range from 4.47 to 35.41, the median cost is 14.14, which suggests that most customers place mid-range orders rather than high-value purchases. The relatively higher standard deviation in cost compared to time variables indicates greater variability in spending behavior.

Food preparation time shows limited dispersion (std ≈ 4.63), with 75% of meals prepared in under 31 minutes. This suggests operational consistency across restaurants, with no evidence of extreme delays.

Delivery time presents a similar pattern, with a median of 25 minutes and relatively tight interquartile range (20–28 minutes). This indicates stable logistics performance.

Importantly, both preparation and delivery times have moderate variability but remain within controlled limits, suggesting that the main performance improvements may come from optimizing efficiency rather than addressing major operational breakdowns.
"""

columns = ["cost_of_the_order", "food_preparation_time", "delivery_time"]

plt.figure(figsize=(18, 5))  # Create one wide figure

for i, col in enumerate(columns, 1):
    plt.subplot(1, 3, i)  # 1 row, 3 columns, position i
    plt.hist(df_clean[col].dropna(), bins=30, color="purple", edgecolor="black")  # Plot histogram removing NaNs, using 30 bins, purple bars, and black edges
    plt.title(f"Distribution of {col}", fontweight="bold") # Title
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.grid(True, linestyle="--", alpha=0.6)

plt.tight_layout()  # Adjust spacing between plots
plt.show()

"""#### Observations:

The distribution of order cost appears moderately right-skewed, with a higher concentration of orders in the lower-to-mid price range (approximately $10–$18). Fewer high-cost orders suggest that most customers prefer moderately priced meals rather than premium-priced options.

The food preparation time distribution is relatively uniform between 20 and 35 minutes, with no strong skewness. This indicates consistent kitchen performance across restaurants, without extreme preparation delays.

The delivery time shows slightly more clustering between 24 and 30 minutes, suggesting that most deliveries are completed within a narrow operational window. The absence of extreme outliers indicates stable logistics performance.

Overall, variability in cost is noticeably higher than variability in preparation or delivery time, implying that customer spending behavior is more diverse than operational performance metrics.
"""

columns = ["cost_of_the_order", "food_preparation_time", "delivery_time"]

plt.figure(figsize=(15, 3))

for i, col in enumerate(columns, 1):
    plt.subplot(1, 3, i)
    sns.boxplot(x=df_clean[col], color="mediumseagreen")  # Green boxplot
    plt.title(f"Boxplot of {col}", fontweight="bold")
    plt.grid(True, linestyle="--", alpha=0.4)

plt.tight_layout()
plt.show()

"""#### Observations:

The boxplot for order cost shows moderate variability, with a median around the mid-range of the distribution and a wider spread compared to the time variables. This indicates greater diversity in customer spending behavior.

The food preparation time displays a relatively compact interquartile range, suggesting consistent kitchen performance across restaurants. There are no significant extreme outliers, indicating stable preparation processes.

Similarly, the delivery time distribution is tightly clustered, with limited dispersion and no pronounced outliers. This reflects controlled delivery operations and reliable logistics performance.
"""

cat_cols = ["day_of_the_week", "cuisine_type", "rating_label"]  # Categorical columns to visualize

plt.figure(figsize=(20, 5))  # Create one wide figure for all countplots

for i, col in enumerate(cat_cols, 1):
    plt.subplot(1, 3, i)  # 1 row, 3 columns layout

    sns.countplot(
        data=df_clean,
        x=col,
        order=df_clean[col].value_counts().index,  # Sort categories by frequency
        color="mediumpurple"  # Set bar color
    )

    plt.title(f"Distribution of {col}", fontweight="bold")
    plt.xticks(rotation=30, ha="right")  # Rotate labels for readability
    plt.grid(axis="y", linestyle="--", alpha=0.4)  # Add horizontal grid only

plt.tight_layout()

"""#### Observations:

Orders are significantly higher during weekends compared to weekdays, indicating stronger demand and potential peak operational load on Saturdays and Sundays.

In terms of cuisine preferences, a few categories (such as American and Japanese) dominate the distribution, while several cuisines have very low order volumes. This suggests demand concentration and highlights key revenue-driving categories.

Regarding customer feedback, a large portion of orders are “Not given”, meaning many customers do not provide ratings. Among rated orders, most ratings are 4 and 5, indicating generally high customer satisfaction. However, the high number of non-rated orders may limit the reliability of satisfaction-based conclusions.
"""

plt.figure(figsize=(4, 4))  # Create figure with better proportions

sns.countplot(data=df_clean, x="day_of_the_week", order=df_clean["day_of_the_week"].value_counts().index, color="paleturquoise")

plt.title("Orders by Day of the Week", fontweight="bold")  # Add bold title
plt.xlabel("Day of the Week")
plt.ylabel("Number of Orders")

plt.grid(axis="y", linestyle="--", alpha=0.4)  # Add horizontal grid for readability
plt.tight_layout()  # Adjust spacing
plt.show()

top10_cuisine = df_clean["cuisine_type"].value_counts().head(10).index

plt.figure(figsize=(8,4))
sns.countplot(data=df_clean, y="cuisine_type",
              order=top10_cuisine)
plt.title("Top 10 Cuisine Types")
plt.show()

top10 = df_clean["restaurant_name"].value_counts().head(10)

plt.figure(figsize=(7, 4))

sns.barplot(
    x=top10.values,      # Number of orders
    y=top10.index,       # Restaurant names
    color="darkorange"     # Soft color
)

plt.title("Top 10 Restaurants by Orders", fontweight="bold")
plt.xlabel("Number of Orders")
plt.ylabel("Restaurant Name")

plt.grid(axis="x", linestyle="--", alpha=0.4)  # Horizontal grid for readability
plt.tight_layout()
plt.show()

"""#### Observations:

Order demand is concentrated among a few restaurants, with Shake Shack leading by a clear margin. The top restaurants generate significantly more orders than others, indicating strong brand preference and demand concentration.
"""

rating_counts = df_clean["rating_label"].value_counts()

plt.figure(figsize=(5, 5))  # Square figure for better proportions

plt.pie(
    rating_counts,
    labels=rating_counts.index,
    autopct="%1.1f%%",  # Show percentages
    startangle=90,      # Start from top
)

plt.title("Rating Distribution", fontweight="bold")
plt.tight_layout()
plt.show()

"""### **Question 7**: Which are the top 5 restaurants in terms of the number of orders received? [1 mark]"""

# Get the top 5 restaurants by number of orders
top5_rest = (
    df_clean["restaurant_name"]      # Select restaurant column
    .value_counts()                  # Count number of orders per restaurant
    .head(5)                         # Keep top 5
    .reset_index()                   # Convert to DataFrame
)

top5_rest.columns = ["restaurant_name", "num_orders"] # Rename columns for clarity
top5_rest = top5_rest.sort_values(by="num_orders", ascending=False) # Sort explicitly (optional, but ensures correct descending order)
top5_rest.style.background_gradient(cmap="Oranges").set_caption("Top 5 Restaurants by Number of Orders") # Display styled table

"""#### Observations:

Shake Shack leads with 219 orders, significantly higher than the next restaurant. The top 5 restaurants show a clear demand concentration, with a sharp drop after the first position, indicating that a few restaurants dominate the platform's order volume.

#### Observations:

### **Question 8**: Which is the most popular cuisine on weekends? [1 mark]
"""

weekend = df_clean[df_clean["day_of_the_week"].str.lower() == "weekend"]  # Filter rows where the day is weekend (case-insensitive)
popular_weekend_cuisine = weekend["cuisine_type"].value_counts().head(1)  # Get the most ordered cuisine on weekends
popular_weekend_cuisine  # Display result

"""#### Observations:

American cuisine is the most popular on weekends, with 415 orders, indicating strong customer preference for this category during peak demand periods.

### **Question 9**: What percentage of the orders cost more than 20 dollars? [2 marks]
"""

pct_over_20 = (df_clean["cost_of_the_order"] > 20).mean() * 100  # Calculate percentage of orders with cost greater than 20
pct_over_20  # Display the percentage

"""#### Observations:

Approximately 29.24% of orders cost more than $20, meaning that about one-third of purchases fall into the higher price range, while the majority of orders remain in the mid-to-lower price segment.

"""

pct_over_20 = (df_clean["cost_of_the_order"] > 20).mean() * 100 # Calculate percentages
pct_under_20 = 100 - pct_over_20
plt.figure(figsize=(7, 4))

bars = plt.bar(["≤ 20", "> 20"], [pct_under_20, pct_over_20], color=["mediumseagreen", "purple"])

plt.title("Percentage of Orders by Cost Threshold", fontweight="bold")
plt.ylabel("Percentage (%)")

# Add percentage labels on top of bars
for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f"{height:.1f}%",
        ha="center",
        va="bottom",
        fontweight="bold"
    )

plt.ylim(0, 100)
plt.grid(axis="y", linestyle="--", alpha=0.3)  # Subtle horizontal grid
plt.tight_layout()
plt.show()

"""#### Observations:

The chart indicates that 70.8% of orders cost $20 or less, while 29.2% exceed $20, showing that most customers prefer mid-range or budget-friendly meals. This suggests a degree of price sensitivity and that demand is largely driven by affordability.

Although higher-cost orders represent a smaller share of total transactions, they may contribute more significantly to revenue due to their larger ticket value. This highlights an opportunity for FoodHub to increase average order value through strategic promotions while maintaining strong volume in the lower-cost segment.

### **Question 10**: What is the mean order delivery time? [1 mark]
"""

df_clean["delivery_time"].mean()  # Calculate the average delivery time

"""#### Observations:

The mean delivery time is approximately 24.16 minutes, indicating that, on average, orders are delivered within about 24 minutes. This reflects relatively efficient and consistent delivery operations.

### **Question 11:** The company has decided to give 20% discount vouchers to the top 3 most frequent customers. Find the IDs of these customers and the number of orders they placed. [1 mark]
"""

# Get the top 3 customers by number of orders
top3_customers = (
    df_clean["customer_id"]   # Select customer ID column
    .value_counts()           # Count orders per customer
    .head(3)                  # Keep top 3 customers
    .reset_index()            # Convert result into DataFrame
)

top3_customers.columns = ["customer_id", "num_orders"]  # Rename columns for clarity

top3_customers  # Display result

"""#### Observations:

The top 3 most frequent customers are ID 52832 (13 orders), 47440 (10 orders), and 83287 (9 orders). These customers show high engagement levels and are strong candidates for loyalty incentives, such as discount vouchers, to encourage retention and repeat purchases.

## **Multivariate Analysis**

### **Question 12**: Perform a multivariate analysis to explore relationships between the important variables in the dataset. (It is a good idea to explore relations between numerical variables as well as relations between numerical and categorical variables) [10 marks]
"""

num_cols = ["cost_of_the_order", "food_preparation_time", "delivery_time", "rating"]  # Select numerical columns
corr = df_clean[num_cols].corr(numeric_only=True)  # Compute correlation matrix (numeric variables only)
corr

"""#### Observations:

The correlation matrix shows very weak relationships between the numerical variables. Order cost has almost no correlation with preparation time (0.04) or delivery time (-0.03), indicating that higher-priced orders do not necessarily take longer to prepare or deliver.

Similarly, customer rating has near-zero correlation with cost (0.03), preparation time (-0.006), and delivery time (-0.009). This suggests that ratings are not strongly driven by price or operational time variables.

The absence of strong correlations indicates that customer satisfaction may depend on factors not captured in this dataset, such as food quality, service experience, or individual preferences. Operational times appear relatively independent from order pricing, reflecting stable and consistent processes.

"""

plt.figure(figsize=(6,4)) # Create figure
sns.heatmap(corr, annot=True, fmt=".2f")
plt.title("Correlation heatmap")
plt.show()

"""#### Observations:

The heatmap shows very weak correlations among all variables (values close to 0). Order cost, preparation time, delivery time, and rating are largely independent of one another. This suggests that customer ratings are not significantly influenced by cost or operational times, and operational performance remains stable across different price levels.
"""

plt.figure(figsize=(6,4))
sns.heatmap(corr, annot=True, fmt=".2f")
plt.title("Correlation heatmap")
plt.show()

"""##### Observations:

The heatmap shows negligible correlations among cost, preparation time, and delivery time (values close to 0). This indicates that order price does not meaningfully affect preparation or delivery time, and operational performance appears independent of order value.
"""

rated = df_clean.dropna(subset=["rating"])
plt.figure(figsize=(14, 5))  # Create one wide figure for both scatter plots

# --- Plot 1: Rating vs Food Preparation Time ---
plt.subplot(1, 2, 1)  # 1 row, 2 columns, position 1
sns.scatterplot(
    data=rated,
    x="food_preparation_time",
    y="rating",
    color="mediumaquamarine",
    alpha=0.6  # Add transparency to reduce overlap
)
plt.title("Rating vs Food Preparation Time", fontweight="bold")
plt.xlabel("Food Preparation Time")
plt.ylabel("Rating")
plt.grid(True, linestyle="--", alpha=0.3)

# --- Plot 2: Rating vs Delivery Time ---
plt.subplot(1, 2, 2)  # 1 row, 2 columns, position 2
sns.scatterplot(
    data=rated,
    x="delivery_time",
    y="rating",
    color="mediumpurple",  # Different but harmonious color
    alpha=0.6
)
plt.title("Rating vs Delivery Time", fontweight="bold")
plt.xlabel("Delivery Time")
plt.ylabel("Rating")
plt.grid(True, linestyle="--", alpha=0.3)

plt.tight_layout()  # Adjust spacing
plt.show()

"""#### Observations:

The scatterplots suggest that ratings remain consistently high (mostly 4 and 5) across the full range of both preparation and delivery times, with no visible downward trend as time increases. This indicates that within the observed operational window (20–35 minutes for preparation and 15–33 minutes for delivery), variations in time do not meaningfully affect customer satisfaction. In other words, delivery performance appears to be within an acceptable threshold for customers. It is possible that other factors—such as food quality, brand reputation, or overall experience—play a more significant role in determining ratings than minor differences in preparation or delivery duration.
"""

plt.figure(figsize=(6,4))
sns.scatterplot(data=rated, x="cost_of_the_order", y="rating")
plt.title("Rating vs Cost")
plt.show()

"""#### Observations:

The scatterplot shows no clear pattern between order cost and rating, as ratings remain consistently distributed between 3 and 5 across all price levels. Both low-cost and high-cost orders receive similar ratings, indicating that higher spending does not necessarily translate into higher customer satisfaction. This suggests that customers evaluate their experience based on factors other than price, such as food quality, service reliability, or brand expectations.
"""

plt.figure(figsize=(5, 5))

sns.boxplot(data=df_clean, x="day_of_the_week", y="delivery_time", color="goldenrod")

plt.title("Delivery Time by Day of the Week", fontweight="bold")
plt.xlabel("Day of the Week")
plt.ylabel("Delivery Time")

plt.xticks(rotation=20)
plt.grid(axis="y", linestyle="--", alpha=0.3)

plt.tight_layout()
plt.show()

"""#### Observations:

Delivery times are higher on weekdays than on weekends, with a median around 28 minutes on weekdays compared to approximately 22 minutes on weekends. Weekdays also exhibit a higher upper range, indicating slightly longer maximum delivery times. Operational efficiency may be lower during weekdays, potentially due to traffic conditions, higher order dispersion, or staffing differences. Despite this variation, delivery times remain within a relatively controlled range overall.
"""

top_cuisines = df_clean["cuisine_type"].value_counts().head(10).index # Get top 10 cuisines by frequency
plt.figure(figsize=(10,4))
sns.boxplot(data=df_clean[df_clean["cuisine_type"].isin(top_cuisines)],
            x="cuisine_type", y="cost_of_the_order")
plt.title("Cost by cuisine (top 10)")
plt.xticks(rotation=30, ha="right")
plt.show()

"""#### Observations:

Noticeable differences in pricing across cuisine types. French and Thai cuisines tend to have higher median order costs compared to others, suggesting they occupy a more premium segment. In contrast, cuisines such as Japanese, American, and Chinese exhibit lower median costs, indicating more mid-range pricing.

Most cuisines show a similar spread in prices, but some (like Mediterranean and Middle Eastern) display wider variability and occasional high-cost outliers. Overall, while price ranges overlap across cuisines, certain categories clearly position themselves at higher price points, which may influence revenue strategies and targeted promotions.

### **Question 13:** The company wants to provide a promotional offer in the advertisement of the restaurants. The condition to get the offer is that the restaurants must have a rating count of more than 50 and the average rating should be greater than 4. Find the restaurants fulfilling the criteria to get the promotional offer. [3 marks]
"""

df_clean["rating"] = pd.to_numeric(df_clean["rating"], errors="coerce")

# Round average rating for cleaner display
promo_eligible["avg_rating"] = promo_eligible["avg_rating"].round(2)

# Sort by average rating and rating count (descending)
promo_eligible = promo_eligible.sort_values(
    by=["avg_rating", "rating_count"],
    ascending=False
)

promo_eligible.style \
    .background_gradient(subset=["avg_rating"], cmap="Greens") \
    .background_gradient(subset=["rating_count"], cmap="Oranges") \
    .set_caption("Restaurants Eligible for Promotional Offer") \
    .format({"avg_rating": "{:.2f}"})

"""#### Observations:

The restaurants that meet the promotional criteria (more than 50 ratings and an average rating above 4) are The Meatball Shop, Blue Ribbon Fried Chicken, Shake Shack, and Blue Ribbon Sushi. Among them, The Meatball Shop has the highest average rating (4.51), while Shake Shack stands out with the largest number of ratings (133), indicating both strong customer satisfaction and high engagement. These restaurants are strong candidates for promotional campaigns due to their proven popularity and positive customer perception.
"""

df_clean["rating"] = pd.to_numeric(df_clean["rating"], errors="coerce")

# Compute rating count and average rating per restaurant
promo_all = (
    df_clean.dropna(subset=["rating"])
    .groupby("restaurant_name")["rating"]
    .agg(rating_count="count", avg_rating="mean")
    .reset_index()
)

# Create eligibility flag
promo_all["eligible"] = np.where(
    (promo_all["rating_count"] > 50) & (promo_all["avg_rating"] > 4),
    "Eligible",
    "Not Eligible"
)

plt.figure(figsize=(10, 6))

# Scatter plot
sns.scatterplot(
    data=promo_all,
    x="rating_count",
    y="avg_rating",
    hue="eligible",
    palette={"Eligible": "green", "Not Eligible": "lightgray"},
    alpha=0.7
)

# Add threshold lines
plt.axvline(50, color="red", linestyle="--")
plt.axhline(4, color="blue", linestyle="--")

# Add labels ONLY to eligible restaurants
for _, row in promo_all[promo_all["eligible"] == "Eligible"].iterrows():
    plt.text(
        row["rating_count"],
        row["avg_rating"],
        row["restaurant_name"],
        fontsize=9,
        ha="left",
        va="bottom"
    )

plt.title("Promotional Offer Eligibility Criteria", fontweight="bold")
plt.xlabel("Rating Count")
plt.ylabel("Average Rating")

plt.grid(True, linestyle="--", alpha=0.3)
plt.tight_layout()
plt.show()

"""#### Observations:

The scatter plot illustrates restaurant eligibility for a promotional offer based on two criteria: rating count greater than 50 (vertical red dashed line) and average rating above 4 (horizontal blue dashed line).

Restaurants located in the upper-right quadrant meet both conditions and are marked in green as eligible. These include Shake Shack, The Meatball Shop, Blue Ribbon Fried Chicken, and Blue Ribbon Sushi. Shake Shack stands out with the highest rating count, while The Meatball Shop has the highest average rating among eligible restaurants.

Most other restaurants fall to the left of the vertical threshold (fewer than 50 ratings), making them ineligible despite some having high average ratings. This visualization clearly shows that eligibility depends not only on quality (rating level) but also on sufficient customer engagement (number of ratings).

### **Question 14:** The company charges the restaurant 25% on the orders having cost greater than 20 dollars and 15% on the orders having cost greater than 5 dollars. Find the net revenue generated by the company across all orders. [3 marks]
"""

def commission_rate(cost):  # Function to determine commission rate based on order cost
    if cost > 20: return 0.25  # 25% commission if cost > 20 dollars
    elif cost > 5: return 0.15  # 15% commission if cost > 5 dollars
    else: return 0.0  # No commission if cost ≤ 5 dollars

df_rev = df_clean.copy()  # Create a copy of the cleaned dataset
df_rev["commission_rate"] = df_rev["cost_of_the_order"].apply(commission_rate)  # Apply commission rule to each order
df_rev["revenue"] = df_rev["cost_of_the_order"] * df_rev["commission_rate"]  # Calculate revenue per order
net_revenue = df_rev["revenue"].sum()  # Sum all revenues to get total net revenue
net_revenue  # Displays the total net revenue generated across all orders

"""#### Observations:

The total net revenue generated from commissions across all orders is $6,166.30. This reflects the platform’s earnings under a tiered commission structure, where higher-value orders (> $20) are charged a 25% commission and mid-range orders (> $5) are charged 15%.

Given that nearly 71% of orders are priced at $20 or below, most revenue is likely driven by the 15% commission tier, while a smaller portion of higher-cost orders contributes disproportionately due to the higher 25% commission rate. This suggests that although high-value orders represent a smaller volume, they play a strategic role in revenue maximization.

The revenue structure incentivizes increasing average order value, as even small shifts in customer spending above the $20 threshold could significantly increase commission earnings. From a strategic perspective, FoodHub could benefit from promoting premium restaurants, bundled deals, or upselling strategies to move more transactions into the higher commission bracket.

### **Question 15:** The company wants to analyze the total time required to deliver the food. What percentage of orders take more than 60 minutes to get delivered from the time the order is placed? (The food has to be prepared and then delivered.) [2 marks]
"""

df_time = df_clean.copy()  # Create a copy of the original DataFrame to avoid modifying it directly
df_time["total_time"] = df_time["food_preparation_time"] + df_time["delivery_time"]  # Sum preparation and delivery times to get the total time

pct_over_60 = (df_time["total_time"] > 60).mean() * 100  # Calculate the percentage of orders where total time exceeds 60 minutes
pct_over_60  # Display the calculated percentage

"""#### Observations:

Approximately 10.54% of orders take more than 60 minutes from placement to delivery (including both preparation and delivery time).

This indicates that nearly 1 in 10 orders experiences relatively long fulfillment times, which may negatively impact customer satisfaction, especially in a food delivery context where speed is a key expectation. However, the majority (almost 89.5%) of orders are delivered within one hour, suggesting overall operational performance is reasonably efficient.

From a business perspective, this 10% segment represents a critical improvement opportunity. These delays could be associated with peak demand periods, specific restaurants, longer delivery distances, or operational bottlenecks. Identifying the drivers behind these longer orders could help reduce late deliveries, improve ratings, and increase customer retention.

### **Question 16:** The company wants to analyze the delivery time of the orders on weekdays and weekends. How does the mean delivery time vary during weekdays and weekends? [2 marks]
"""

mean_delivery_by_day = df_clean.groupby("day_of_the_week")["delivery_time"].mean() # Group orders by day of the week and calculate the mean delivery time for each day

mean_delivery_by_day # Display the result

"""#### Observations:

The mean delivery time is 28.34 minutes on weekdays and 22.47 minutes on weekends. This indicates that deliveries take, on average, nearly 6 minutes longer during weekdays.

This difference may be explained by heavier traffic conditions, higher operational constraints, or workday congestion affecting logistics during weekdays. Conversely, weekends may allow for smoother traffic flow and faster dispatching, even if order volumes are high.

Operationally, this suggests that weekday performance is more constrained and may benefit from optimization strategies such as improved routing, staffing adjustments, or peak-hour resource allocation.

## **Conclusion and Recommendations**

### **Question 17:** What are your conclusions from the analysis? What recommendations would you like to share to help improve the business? (You can use cuisine type and feedback ratings to drive your business recommendations.) [6 marks]

### Conclusions:

* Demand is weekend-heavy. Orders are noticeably higher on weekends than weekdays, which confirms weekends as the platform’s peak-demand period. This has direct implications for staffing, delivery capacity, and promotional timing.

* A few cuisines drive most orders. Cuisine demand is concentrated: American cuisine is the most popular on weekends (415 orders), and the overall cuisine distribution shows a small set of cuisines generating most of the volume, while many cuisines have low frequency. This indicates clear “core categories” that sustain platform activity.

* Restaurant demand is highly concentrated. The platform is not evenly distributed across restaurants. A small group of restaurants dominates order volume. For example, the top restaurants include Shake Shack (219 orders), The Meatball Shop (132), Blue Ribbon Sushi (119), Blue Ribbon Fried Chicken (96), and Parm (68). This suggests FoodHub depends strongly on a handful of key partners.

* Operational performance is stable overall, but a meaningful minority of orders are slow. Food preparation time ranges 20–35 minutes with an average of ~27.37 minutes, and delivery time averages ~24.16 minutes. However, when combining both stages, ~10.54% of orders exceed 60 minutes, meaning roughly 1 in 10 orders may be perceived as “late” and represent a risk for customer satisfaction and retention.

* Weekday deliveries are slower than weekend deliveries. Mean delivery time is ~28.34 minutes on weekdays versus ~22.47 minutes on weekends, a difference of almost 6 minutes. This suggests weekday friction (e.g., traffic or operational constraints) is a consistent driver of slower service.

* Customer satisfaction is generally high among rated orders, but ratings coverage is a major limitation. A large portion of orders have no rating (736 “Not given”), which reduces the representativeness of satisfaction analyses. Among rated orders, ratings cluster mostly at 4–5, suggesting positive experiences when feedback is provided.

* Ratings are not strongly explained by cost or time in this dataset. Correlation values between rating and cost/prep/delivery time are near zero, and scatterplots show no clear trend. This suggests satisfaction is likely influenced by factors not captured here (e.g., food quality, packaging, accuracy, restaurant consistency, customer expectations).

* Revenue is meaningful and can be optimized through order value strategy. Under the commission rules (25% for orders > $20, 15% for orders > $5), total net revenue across all orders is $6,166.30. Also, ~29.24% of orders are above $20, indicating a sizable premium segment that can strongly impact commission earnings.

* Promotion-eligible restaurants are clear and defensible. Restaurants meeting the campaign criteria (>50 ratings and avg rating >4) are: The Meatball Shop, Blue Ribbon Fried Chicken, Shake Shack, and Blue Ribbon Sushi. Among these, The Meatball Shop has the highest average rating (~4.51) and Shake Shack has the highest rating count (~133), indicating both strong perceived quality and strong customer engagement.

### Recommendations:

*A) Demand & Growth Strategy*

* Double down on weekend-focused campaigns. Since weekends drive the most orders, schedule major promotions and featured placements (home page banners, push notifications) on weekends to maximize conversion. Consider weekend bundles tied to the most popular cuisine (American) to leverage established demand.
* Use cuisine insights to structure the marketplace. Prioritize top cuisines (especially American, and other high-frequency cuisines such as Japanese) in discovery features (“Popular this weekend”, “Top cuisines near you”). For low-volume cuisines, rotate visibility or run targeted discovery campaigns to test whether demand can be grown without hurting core performance.
* Segment pricing strategy using the $20 threshold. Since 70.8% of orders are ≤ $20 and 29.2% are > $20, use two tactics:
* Value segment (≤ $20): bundles, free-delivery thresholds, add-on suggestions (drinks/desserts) to lift average basket size.
* Premium segment (> $20): highlight premium cuisines (e.g., French/Thai have higher medians) and premium restaurants, with curated “Premium Picks” collections. This can increase the share of high-margin orders and improve total commission revenue.

*B) Restaurant Partnership & Promotions*

* Prioritize key partners that dominate volume. Restaurants like Shake Shack and the next top performers contribute disproportionate order volume. Ensure these partners have strong operational support (accurate prep times, pickup readiness) and consider co-marketing agreements because their performance heavily influences platform-level KPIs.
* Promote only high-confidence restaurants using your eligibility rule. Your eligibility scatterplot is excellent because it balances quality (avg rating >4) and reliability of measurement (rating count >50). Use the eligible set for ad placements and “recommended” badges to protect customer trust.
* Help high-rated but low-sample restaurants grow responsibly. Many restaurants appear to have high ratings but low rating counts (left side of the plot). Create a “Rising Stars” program where these restaurants get limited exposure plus tight monitoring (prep time SLA, cancellation rate if available). This grows supply diversity without risking customer experience.

*C) Operations & Customer Experience*

* Attack the 60+ minute orders as a targeted service-quality initiative. Since ~10.54% exceed 60 minutes, this bucket should be analyzed and reduced. Practical actions:
* Identify whether delays are mostly from prep or delivery (e.g., compute percent where prep_time > 35, delivery_time > 33, or total_time > 60 by component).
* Flag restaurants frequently associated with long prep times and work with them on batching and readiness.
* Improve courier dispatching/routing for orders predicted to exceed 60 minutes.
* Improve weekday delivery performance specifically. Weekdays are ~6 minutes slower on average. Consider:
* Higher courier supply during weekday peak windows (lunch/dinner)
* Routing optimization / zone-based batching
* Restaurant pickup coordination (reduce waiting time)
Even a 2–3 minute weekday reduction could materially improve perceived service.

*D) Ratings & Feedback Quality (Critical for Better Models)*

* Reduce “Not given” ratings through gentle nudges and incentives. With 736 unrated orders, satisfaction insights are limited. Use lightweight nudges:
* 1-tap rating prompt right after delivery
* small incentives (e.g., points/credits) for rating completion
* ask for rating only on a subset if you want to avoid fatigue
* More ratings improve the reliability of restaurant-level decisions and promotion eligibility.
* Use rating + volume together, not rating alone. Keep using the rule “high rating + enough rating count” for decisions. This avoids overreacting to small-sample noise and keeps recommendations trustworthy.

--------------------------------------------------------------------------------
"""